# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumers',
            name='full_name',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='consumers',
            name='gender',
            field=models.CharField(choices=[('male', 'Чоловіча'), ('female', 'Жіноча')], max_length=100),
        ),
    ]
