# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20170624_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_slug',
            field=models.CharField(blank=True, max_length=700),
        ),
    ]
