# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20170624_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumers',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Чоловіча'), ('female', 'Жіноча')], max_length=100),
        ),
    ]
